version: '3'
services:
  homer:
    container_name: homer
    image: b4bz/homer:latest
    ports:
      - "8082:8080"
    volumes:
      - ./assets:/www/assets
    restart: unless-stopped
    networks:
      - mynetwork

networks:
  mynetwork:
    external: true